import type { Oportunidad, PreguntaDura, Productor, Proveedor } from "@/types/domain";

export const productores: Productor[] = [
  {
    id: "prod-001",
    nombre: "Vilma Jeanneth Guardado de Ayala",
    rubro: "Alimentos y Bebidas",
    ubicacion: "Cantón El Zapote, San Juan Opico, La Libertad",
    capacidad: "500 almuerzos/día",
    telefono: "+50377234567",
    experienciaEstado: "Ninguna",
    ingresoMensual: 3000,
    nombreNegocio: "Comedor El Sazón de Vilma",
    antiguedadAnos: 8,
    empleados: 5,
  },
  {
    id: "prod-002",
    nombre: "José Santos Rivera Meléndez",
    rubro: "Textiles y Uniformes",
    ubicacion: "Soyapango, San Salvador",
    capacidad: "2,000 uniformes/mes",
    telefono: "+50361234567",
    experienciaEstado: "3 licitaciones MINEDUCYT, 2 ganadas",
    ingresoMensual: 8500,
    nombreNegocio: "Taller Rivera",
    antiguedadAnos: 20,
    empleados: 12,
  },
  {
    id: "prod-003",
    nombre: "Carlos Alberto Bonilla Portillo",
    rubro: "Construccion y Mantenimiento",
    ubicacion: "San Miguel, San Miguel",
    capacidad: "Proyectos hasta $200,000",
    telefono: "+50361237890",
    experienciaEstado: "3 alcaldías, RUPES activo",
    ingresoMensual: 12000,
    nombreNegocio: "Bonilla Construcciones",
    antiguedadAnos: 15,
    empleados: 15,
  },
  {
    id: "prod-004",
    nombre: "Rosa Amelia Quintanilla de López",
    rubro: "Suministros Agricolas",
    ubicacion: "Usulután, Usulután",
    capacidad: "200 quintales maíz/cosecha",
    telefono: "+50363456789",
    experienciaEstado: "2 contrataciones directas con MAG",
    ingresoMensual: 4500,
    nombreNegocio: "Cooperativa Cosechas del Pacífico",
    antiguedadAnos: 10,
    empleados: 8,
  },
];

export const oportunidades: Oportunidad[] = [
  {
    id: "opp-001",
    titulo: "Servicio de Alimentación Escolar - Distrito 04-25 - MINEDUCYT",
    institucion: "MINEDUCYT",
    monto: 48750,
    fechaCierre: "2026-07-18",
    rubroRequerido: "Alimentos y Bebidas",
    unspscCode: "50200000",
    urlFuente: "https://www.comprasal.gob.sv/licitaciones/lp-07-2026-mined",
    tipoContratacion: "Licitación Pública",
  },
  {
    id: "opp-002",
    titulo: "Servicio de Cafetería - Edificio Central ANDA",
    institucion: "ANDA",
    monto: 28400,
    fechaCierre: "2026-07-22",
    rubroRequerido: "Alimentos y Bebidas",
    unspscCode: "50200000",
    urlFuente: "https://www.comprasal.gob.sv/libre-gestion/lg-12-2026-anda",
    tipoContratacion: "Libre Gestión",
  },
  {
    id: "opp-003",
    titulo: "Confección de Uniformes para Personal Hospitalario - ISSS",
    institucion: "ISSS",
    monto: 12680,
    fechaCierre: "2026-07-12",
    rubroRequerido: "Textiles y Uniformes",
    unspscCode: "53000000",
    urlFuente: "https://www.comprasal.gob.sv/licitaciones/li-03-2026-isss",
    tipoContratacion: "Licitación Pública",
  },
  {
    id: "opp-004",
    titulo: "Suministro de Frutas y Vegetales Deshidratados - MAG",
    institucion: "MAG",
    monto: 3250,
    fechaCierre: "2026-07-08",
    rubroRequerido: "Alimentos y Bebidas",
    unspscCode: "51120000",
    urlFuente: "https://www.comprasal.gob.sv/contrataciones/cd-05-2026-mag",
    tipoContratacion: "Contratación Directa",
  },
  {
    id: "opp-008",
    titulo: "Suministro de 1,500 Uniformes para Agentes PNC",
    institucion: "PNC",
    monto: 95000,
    fechaCierre: "2026-07-25",
    rubroRequerido: "Textiles y Uniformes",
    unspscCode: "53000000",
    urlFuente: "https://www.comprasal.gob.sv/licitaciones/lp-09-2026-pnc",
    tipoContratacion: "Licitación Pública",
  },
  {
    id: "opp-009",
    titulo: "Mantenimiento Edificios Gubernamentales - Casa Presidencial",
    institucion: "Casa Presidencial",
    monto: 78000,
    fechaCierre: "2026-07-30",
    rubroRequerido: "Construccion y Mantenimiento",
    unspscCode: "72100000",
    urlFuente: "https://www.comprasal.gob.sv/licitaciones/lp-11-2026-presi",
    tipoContratacion: "Licitación Pública",
  },
  {
    id: "opp-016",
    titulo: "Alimentación Personal Penitenciario - San Vicente",
    institucion: "Dirección General de Centros Penales",
    monto: 56000,
    fechaCierre: "2026-07-29",
    rubroRequerido: "Alimentos y Bebidas",
    unspscCode: "50200000",
    urlFuente: "https://www.comprasal.gob.sv/licitaciones/lp-14-2026-dgcp",
    tipoContratacion: "Licitación Pública",
  },
  {
    id: "opp-019",
    titulo: "Compra Material Ferretería Obras Comunales - FODES",
    institucion: "FODES",
    monto: 5800,
    fechaCierre: "2026-07-07",
    rubroRequerido: "Construccion y Mantenimiento",
    unspscCode: "72000000",
    urlFuente: "https://www.comprasal.gob.sv/contrataciones/cd-19-2026-fodes",
    tipoContratacion: "Contratación Directa",
  },
];

export const proveedores: Proveedor[] = [
  {
    id: "prov-001",
    nombre: "S&S Alimentos SA de CV",
    rubro: "Alimentos y Bebidas",
    ubicacion: "San Salvador",
    capacidad: "2,000 raciones/día",
    telefono: "+50322567890",
    personalidad: "estrategico",
  },
  {
    id: "prov-002",
    nombre: "Textiles El Sol SA",
    rubro: "Textiles y Uniformes",
    ubicacion: "San Miguel",
    capacidad: "5,000 uniformes/mes",
    telefono: "+50326341234",
    personalidad: "agresivo",
  },
  {
    id: "prov-003",
    nombre: "Confecciones Sivar SA",
    rubro: "Textiles y Uniformes",
    ubicacion: "Santa Tecla",
    capacidad: "2,000 uniformes/mes",
    telefono: "+50322284567",
    personalidad: "conservador",
  },
  {
    id: "prov-005",
    nombre: "Constructora del Valle SA",
    rubro: "Construccion y Mantenimiento",
    ubicacion: "San Vicente",
    capacidad: "Proyectos hasta $500,000",
    telefono: "+50323945678",
    personalidad: "estrategico",
  },
  {
    id: "prov-006",
    nombre: "AgroInsumos SV SA",
    rubro: "Suministros Agricolas",
    ubicacion: "Santa Ana",
    capacidad: "1,000 quintales/mes",
    telefono: "+50324789012",
    personalidad: "agresivo",
  },
];

export const preguntasFallback: PreguntaDura[] = [
  {
    pregunta: "¿Ya calculaste cuánto te cuesta producir cada unidad con los precios actuales?",
    intencion: "Evaluar costos reales antes de ofertar.",
    palabrasClave: ["costo", "margen", "ingredientes", "materiales"],
  },
  {
    pregunta: "¿Tenés flujo de caja para esperar los 60 a 90 días que puede tardar el pago?",
    intencion: "Evaluar liquidez durante el ciclo de pago estatal.",
    palabrasClave: ["flujo", "pago", "esperar", "plazo"],
  },
  {
    pregunta: "Si ganás y sube la demanda, ¿cuál es tu plan B para cumplir sin atrasarte?",
    intencion: "Evaluar capacidad operativa y riesgo de incumplimiento.",
    palabrasClave: ["capacidad", "entrega", "plan", "riesgo"],
  },
];
